[project]
name = "concurrentandparallel"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []


[tool.ruff]
line-length = 99

[tool.ruff.lint]
select = ["ALL"]
ignore = ["D100", "D103", "D104", "D105", "ERA001", "D107", "T201"]
unfixable = ["F401"]

[tool.uv.workspace]
members = []
